builds:
  - goos:
      - linux
    hooks:
      post: upx {{ .Path }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

release:
  github:
    owner: shyim
    name: docker-gen

dockers:
  - image_templates:
      - "ghcr.io/shyim/docker-gen:{{ .Tag }}"
      - "ghcr.io/shyim/docker-gen:{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/shyim/docker-gen:latest"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
